import Head from 'next/head'
import Image from 'next/image'
import { useEffect,useState } from 'react';
import styles from '../styles/Home.module.css'

export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>daily catch </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

      <div className={styles.homepage}>
        {/* <a href="./Homelogin.htmll"> */}
        <img src="Frame.png" alt=""/>
    {/* </a> */}
    </div>
    <div className={styles.details}>
       <a className={styles.catch} href="./dailyCatch.html">Daily Catch</a>
       <a className={styles.warehouse} href="#">Warehouse</a>
      
    </div>
    
    </main>
    </div>
    )
    }
