import Head from 'next/head'
import Image from 'next/image'
import { useEffect,useState } from 'react';
import styles from '../styles/Home.module.css'

export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>daily catch </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

      <div className={styles.homepage}>
        {/* <a href="./Homelogin.htmll"> */}
        <img src="Frame.png" alt=""/>
    {/* </a> */}
    </div>
    <div className={styles.details}>
       <a className={styles.catch} href="./dailyCatch.html">Daily Catch</a>
       <a className={styles.warehouse} href="#">Warehouse</a>
      
    </div>

    <div className={styles.column2}>
        <div className={styles.btn}>
            <a href=""><ion-icon name="search-outline"></ion-icon></a>
            <a href=""><ion-icon name="settings"></ion-icon></a>
            <a href="./login.html"><ion-icon name="power-sharp"></ion-icon></a>
            
        </div>
        
        <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
        <script noModule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>

        <p className={styles.helloLabel}>Hello User</p>
        
        <label className={styles.label}>TRAWLING NUMBER</label>
        <input type="text" className={styles.formcontrol}/>
        <label className={styles.label} style={{marginLeft: "365px"}}>TRAWLING DATE</label>
        <input type="text" className={styles.formcontrol} style={{marginLeft: "369px",width: "41px"}}/>
        <input type="text" className={styles.formcontrol} style={{marginLeft: "420px", width: "41px"}}/>
        <input type="text" className={styles.formcontrol} style={{marginLeft: "480px",width: "85px"}}/>
        <label className={styles.label} style={{marginLeft: "712px"}} >TOTAL VOLUME</label>
        <input type="text" className={styles.formcontrol}  style={{marginLeft: "712px"}} />
      
    </div>
    <div className={styles.tablehead}>
        <div >
            <p className={styles.title1}>Type</p>
            <p className={styles.title2}> Category</p>
            <p className={styles.title3}> Grade</p>
            <p className={styles.title4}> No of Boxes</p>
            <p className={styles.title5}> Position</p>
        </div>
        <select className={styles.fishType}> </select>
        <select className={styles.fishcategory}> </select>
        <select className={styles.fishgrade}> </select>
        <input type="text" className={styles.noofboxes}/> 
        <input type="text" className={styles.position}/> 
        <button className={styles.addbutton}>Add</button>
        <button className={styles.savebutton}> Save</button>
        
    </div>
   
      </main>

      
    </div>
  )
}