import Head from 'next/head';
import styles from '../styles/Home.module.css'
import Image from 'next/image'
import axios from 'axios'
import { useEffect, useState } from 'react';
export default function Home() {
    const[loginDetails,setloginDetails] = useState([]);
    const[username,setUsername] = useState('');
    const[password,setPassword] = useState('');
     const handleChange = ( ) =>  {
        this.setState({value:event.target.value});
    }
    useEffect(() => {
        // fetch(
        //     "http://localhost:8080/login", {
        //         method: 'POST',body: {
        //             "user_name": "username1 ",
        //             "password": exports1
        //         }
        //     }
        // ).then( res => res.json()).then(result => console.log(result))

        axios.post("http://localhost:8080/login", {
            "user_name": "username1 ",
            "password": "exports1"
        })
        .then(function (response) {
            console.log(response.data.message);
            if(response.data.message== 'Authorized') {
                window.location.href="/about"
            }

        })
        .catch (function (error){
            console.log(error);
        });
    })

    let login =() => {
        axios.post("http://localhost:8080/login", {
            "user_name": "username1 ",
            "password": exports1
        })
        .then(function (response) {
            console.log(response.data.message);
            if(response.data.message== 'Authorized') {
                window.location.href="/about"
            }

        })
        .catch (function (error){
            console.log(error);
        });
    };

    return (
        <div className={styles.container}>
          <Head>
            <title>Oceanus Login</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
    
          <main className={styles.main}>
          <section>
                    <div className={styles.imgbox}> 
                    <Image  src= "/image1.png"alt= "Ocenaus image" height={621} width={700} />
                    </div>
                </section>
                <div className={styles.contentbx}>
                    
                            <form onSubmit={"handleLogin(event)"}>
                            <Image  className={styles.vector} height="120px" width="100px" src="/Frame.png" alt="vector image"/>
                            <h2 className={styles.h2}>LOGIN</h2>
                            <h3 className={styles.h3}>Welcome to Oceanus </h3>
                            <div className={styles.inputbx}>
                                <input className={styles.input} type="email" id="email" placeholder="Email" name="" value={username} onChange ={e => setUsername(e.target.value)} />
                            </div>
                            <div className={styles.inputbx}>               
                                <input type="password" placeholder="Password" id="password" name="" className={styles.input} value={password} onChange ={e => Password(e.target.value)} />
                            </div>
                            <div className={styles.remember}>
                                <label><input type="checkbox" name=""/> Remember me</label>
                                <span className={styles.forgot}><a  href="https://www.google.com/">Forgot Password </a></span>
                            </div>
    
                           <div className={styles.inputbx}>
                            <button className={styles.button}><a href="./Homelogin.html">LOGIN</a> </button>
                           
                           </div>
    
                        <div id="result" className={styles.display}>
    
                        </div>
                        
                    </form>
                    </div>
                    </main>
                    </div>
    
      )
}